rear_camera_node:
  ros__parameters:
    video_device: /dev/video0  # Path to the video device
    pixel_format: MPEG        # Pixel format (e.g., 'yuyv', 'mjpeg', etc.)
    camera_frame_id: camera_link  # TF frame ID for the camera
    camera_name: my_camera     # Name of the camera, used for naming topics
    image_width: 1920            # Width of the image frame
    image_height: 1080           # Height of the image frame
    framerate: 30                # Desired framerate (frames per second)
    # brightness: 100              # Brightness level (0-255 for most cameras)
    contrast: 128                # Contrast level (0-255 for most cameras)
    saturation: 128              # Saturation level (0-255 for most cameras)
    hue: 0                       # Hue level (0-255 for most cameras, if applicable)
    auto_exposure: 1             # Auto-exposure (1 for auto, 0 for manual)
    exposure: 100                # Exposure time, if auto_exposure is set to 0
    gain: 0                      # Gain level (0-255 for most cameras, if applicable)
    white_balance_auto: 1        # Auto white balance (1 for auto, 0 for manual)
    white_balance: 4000          # White balance temperature, if white_balance_auto is 0
    focus_auto: 1                # Auto focus (1 for auto, 0 for manual)
    focus_absolute: 0            # Manual focus setting, if focus_auto is 0
    pan_absolute: 0              # Pan setting (if supported by the camera)
    tilt_absolute: 0             # Tilt setting (if supported by the camera)
    zoom_absolute: 0             # Zoom setting (if supported by the camera)



    #1.0-090c:337b new usb cams
    #1.0-4c4a:4a55 old usb cams
    #1.0-05a3:9230 rover cam

#     [camera]: 
# >> stream formats:
#    - Pixelformat: MJPEG (320x240 - 1920x1080)
#    - Pixelformat: YUYV (320x240 - 1920x1080)
# [WARN] [1712536526.459334478] [camera]: no pixel format selected, using default: "MJPEG"
# [INFO] [1712536526.459383907] [camera]: 
# >> MJPEG format sizes:
#    - 320x240
#    - 352x288
#    - 640x480
#    - 800x600
#    - 1280x720
#    - 1920x1080